name: major 

on:
  workflow_dispatch:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
    
jobs:
  compliance:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/major.yml@develop
