name: minor

on:
  push:
    # branches:
    #  - develop
  workflow_dispatch:
    inputs:
      semver_restriction_branch_skip:
        description: 'Must be true or false. Default is true'
        required: false
        type: boolean
        default: true
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  compliance:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/minor.yml@develop
