name: minor

on:
  push:
    branches:
      - develop
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  compliance:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/minor.yml@develop
