name: patch

on:
  push:
    branches:
      - 'fix/\d+\.\d+\.x'

permissions:
  contents: write
  pull-requests: write

jobs:
  compliance:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/patch.yml@develop
