name: submodule

on:
  push:
    branches:
      - 'fix/\d+\.\d+\.x'
      - 'develop'

permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository with Submodules
      uses: actions/checkout@v3
      with:
        repository: utilizable/terraform-module
        token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
        submodules: 'recursive'

    - name: Fetch Latest Submodule
      run: |
        git submodule update --init --recursive

