name: terraform 

on:
  push:
    branches:
      - develop

jobs:
  report:
    runs-on: ubuntu-latest
    
    environment: production 
    
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Terraform apply
        run: |
          echo "${{secrets.ENV_PRIV}}" > .env_priv
          make apply
